google/llvm-premerge-checks

scripts/run_cmake.sh
scripts/run_ninja_check-all.sh

That is helpful to debug builds

Use set -x to output commands running

---

README.md
k8s_config
kubernetes/cluster_create.sh
kubernetes/jenkins-staging/Deployment.yaml
kubernetes/jenkins.yaml
kubernetes/nfs.yaml
kubernetes/results-nginx/Deployment.yaml
kubernetes/reverse-proxy/Certificates.yaml
kubernetes/reverse-proxy/Ingress.yaml
kubernetes/reverse-proxy/Namespace.yaml
kubernetes/reverse-proxy/kustomization.yaml

configuration for new GCP project

---

docs/playbooks.md

For now only describing how to get an conduit API token

Add section about local changes

---

scripts/phabtalk/apply_patch.py

Manually specify commit to base patch

---

scripts/phabtalk/apply_patch2.py

- use other commit then master as a base
- recursively find dependent commits
- commit dependent changes before applying main diff
#114

Updates to apply-patch

---

scripts/phabtalk/apply_patch2.py

clang-format does not work properly if applied diff is not staged

stage patch

---

scripts/phabtalk/phabtalk.py

Generate test summary HTML
for #119

Attach artifacts to build

---

scripts/phabtalk/phabtalk.py

+ reworked phab-talk, now it's a class instead of free functions

Generate HTML summary instead of adding comment

---

scripts/phabtalk/apply_patch2.py
scripts/phabtalk/phabtalk.py

* added dryrun for add_artifact()
* fixed issues when buildresult is None

Improving phabtalk

---

scripts/metrics/README.md

A proposal for 1) what metrics we want to collect and 2) how to collect them.

Proposal for metrics

---

docs/playbooks.md
docs/user_doc.md

For the public rollout I updated our documentation.

updated documentation for public rollout

---

scripts/phabtalk/phabtalk.py

add link to build log

---

containers/base-debian/Dockerfile
containers/buildkite-premerge-debian/Dockerfile
containers/buildkite-premerge-debian/bootstrap_build.sh
containers/buildkite-premerge-debian/start_agent.sh
kubernetes/buildkite/agents_premerge.yaml

- added simple script to define pipeline, it will check out from this
repo later
- refactored docker container, e.g. merged most of the RUN steps into
one and moved steps that are likely to change closer to the end. That
should improve rebuild / upload speed.
Sample run: https://buildkite.com/llvm-project/premerge/builds/14

Forked docker image for premerge

---

scripts/buildkite/build_branch_pipeline.py
scripts/buildkite/build_master_pipeline.py

powershell command was not correct. I am surprised this worked at all.

fix build command on windows

---

containers/agent-windows-vs2019/Dockerfile
scripts/buildkite/build_branch_pipeline.py
scripts/buildkite/build_master_pipeline.py
scripts/windows_agent_start_buildkite.ps1

option to disable compilation cache + perl on windows

---

scripts/buildkite/build_master_pipeline.py
scripts/phabtalk/phabtalk.py
scripts/premerge_checks.py
scripts/run_cmake.py
scripts/run_cmake_config.yaml

- additional arguments to set enabled projects, log level and reset
cache.

Print commands to reproduce build locally

---

scripts/buildkite/build_branch_pipeline.py
scripts/choose_projects.py
scripts/run_cmake.py

+ option to skip win / linux build from diff checks

Additional logging for project selection

---

scripts/buildkite/build_branch_pipeline.py
scripts/buildkite/build_master_pipeline.py

retry build step if agent is gone or shut down

---

scripts/clang-format.ignore
scripts/clang_format_report.py

ignore **/test for clang-format

---

Jenkins/BETA-apply-patch/Jenkinsfile
Jenkins/apply-patch/Jenkinsfile
scripts/buildkite/apply_patch.sh
scripts/buildkite/create_branch_pipeline.py
scripts/phabtalk/apply_patch2.py

+ possible fix for base commit
+ ph_ options to control commit behavior

use logging in apply_patch2

---

kubernetes/windows_agent_create.sh
scripts/buildkite/analyze_jobs.ipynb
scripts/buildkite/build_branch_pipeline.py
scripts/buildkite/build_master_pipeline.py

+ updated image for win machines

custom agent constraints

---

docs/playbooks.md
scripts/phabtalk/phabtalk.py
scripts/pipeline_premerge.py
scripts/premerge_checks.py
scripts/set_build_status.py
scripts/summary.py

That is useful when testing pipelines

Don't fail if phabricator target is not specified

---

scripts/buildkite_utils.py
scripts/phabtalk/apply_patch.py
scripts/phabtalk/apply_patch2.py
scripts/phabtalk/phabtalk.py
scripts/pipeline_create_branch.py
scripts/pipeline_premerge.py
scripts/requirements.txt
scripts/steps.py

fixes #192
additionally:
- install python libs after scripts checkout, so we don't need to
rebuild images and restart agents only to add a new python dependency
- updated lib versions
- similar scripts checkout in steps

retry most of the requests with backoff

---

scripts/phabtalk/phabtalk.py
scripts/premerge_checks.py
scripts/run_cmake.py

Added command to create a link to a compilation database and switch
directory to run tidy and format.

More accurate commands to reproduce build

---

docs/playbooks.md
scripts/llvm-dependencies.yaml

related to #271: clang-tidy cannot find gtest/gtest

add clang to flang deps

---

scripts/metrics/repo_hist.py
scripts/metrics/repo_hist_db.py

only looking at libc++ at the moment

improved git metrics script

---

containers/base-debian/Dockerfile
kubernetes/buildkite/linux-agents-test.yaml
scripts/clang_format_report.py
scripts/steps.py

updated llvm version to 12 with relevant fixes in scrips

update linux node pool (machines w/ no external ssd)

---

containers/agent-windows-buildkite/Dockerfile
containers/agent-windows-buildkite/pre-checkout.bat
containers/agent-windows-buildkite/start_agent.ps1
containers/build_run.ps1
scripts/steps.py
scripts/windows/pre-checkout.ps1
scripts/windows/start_container.ps1
scripts/windows/unlock_path.ps1
scripts/windows_agent_start_buildkite.ps1

Kill all running processes in BUILDKITE_BUILD_PATH and force unlock git
folder.

Pre-checkout for windows

---

scripts/llvm-dependencies.yaml
scripts/pipeline_main.py

enable flang

---

containers/buildkite-premerge-debian/Dockerfile
containers/buildkite-premerge-debian/post-checkout

add post-checkout to run git prune

---

containers/buildkite-premerge-debian/post-checkout
docs/playbooks.md
scripts/choose_projects.py
scripts/patch_diff.py
scripts/phabtalk/phabtalk.py
scripts/pipeline_create_branch.py
scripts/pipeline_premerge.py
scripts/steps.py
scripts/summary.py

if user is a member of "bazel_build" https://reviews.llvm.org/project/view/107/
or modified /utils/bazel/*
For #328

Run bazel builds in premerge

---

scripts/pipeline_main.py
scripts/pipeline_premerge.py
scripts/steps.py
scripts/sync_fork.py

- uniformly append env variables
- resolve current HEAD and pass it as BUILDKITE_COMMIT to script
generators. Add it as ph_commit_sha
fixes #337

script to sync fork llvm-premerge-tests/llvm-project

---

scripts/clang_tidy_report.py

See commit messages for details.

Clang tidy non utf8

---

scripts/pipeline_main.py
scripts/steps.py

sample build https://buildkite.com/llvm-project/llvm-main/builds/3258#1c66dc1a-9313-4265-bf37-b08ccb12f86e

Run bazel build on mainline

---

scripts/llvm-dependencies.yaml

Mark libc as unsupported on Windows

---

containers/base-debian/Dockerfile
docs/playbooks.md

Add openmp deps and update toolchain to 13

---

containers/base-debian/Dockerfile
scripts/llvm-dependencies.yaml

HI @metaflow ,
I created an initial configuration based on the discussion around supporting BOLT in #364. Can you please take a look if that covers all the changes we need?
Re-deploying the Debian docker image (with the additional library) is optional. 
Thx,
Christian

Updated configuration for BOLT

---

scripts/patch_diff.py

Reverts google/llvm-premerge-checks#417

Revert "patch_diff: Stop trying to skip landed revisions"

---

scripts/patch_diff.py

Checked by running https://buildkite.com/llvm-project/diff-checks/builds/134962#0184396e-2346-4143-92ca-88e82750b073 (still fails but ).
original PR by @mizvekov  #421

Skip landed diffs

---

scripts/buildkite/sample_build.py
scripts/git_utils.py
scripts/patch_diff.py
scripts/steps.py

index.lock files are likely left from previous git invocations (crashes?) and prevent further repo usage (fixed #424)

Windows vscmd && remove index.lock

---

Pipfile
containers/buildkite-premerge-windows/Dockerfile
containers/buildkite-premerge-windows/post-checkout.bat
containers/buildkite-premerge-windows/pre-checkout.bat
containers/buildkite-premerge-windows/start_agent.ps1
scripts/windows_agent_start_buildkite.ps1

updated win agent

---

scripts/pipeline_main.py
scripts/pipeline_premerge.py

Related to https://reviews.llvm.org/D155078

Move the pipeline generation scripts outside of libc++

---

containers/buildbot-linux/Dockerfile
containers/buildkite-linux/Dockerfile

[Docker] Install tzdata in buildkite-linux.
