.gitignore
Jenkins/Phabricator-pipeline/Jenkinsfile
Jenkins/master-linux-pipeline/Jenkinsfile
Jenkins/master-windows-pipeline/Jenkinsfile
containers/build_run.sh
docs/playbooks.md
scripts/lint.sh
scripts/phabtalk/README.md
scripts/phabtalk/phabtalk.py
scripts/run_cmake.sh
scripts/run_ninja.sh

Attach diffs produced by git-clang-format as lint messages. For #21 
E.g.: https://reviews.llvm.org/D71197?id=233029
Will add a link to file and code to apply the patch in the next PR.
+ don't create TARGET_DIR in scripts;
+ updated section about local build;
+ partially specified inputs / outputs of scripts so it's more transparent what are the results;
+ added symlink to compile_command.json (clang-tidy will need it).

Display results for git-clang-format

---

containers/agent-debian-testing-clang8-ssd/Dockerfile
scripts/lint.sh
scripts/run_cmake.sh

+ add jq to parse conduit responses later
Run in local docker container and it seems to work fine.
for #76

Update image to use default version

---

Jenkins/Phabricator-pipeline/Jenkinsfile
scripts/lint.sh
scripts/phabtalk/phabtalk.py

+ don't assume that clang-format has passed if there is no file.
If linters didn't run at all file will be missing.
+ add "gray" icon for the result if it's unknown.
+ assume whole build is failed if clang-format or clang-tidy found something.
+ combine multiple lint messages per line.

Run clang-tidy and parse message

---

scripts/lint.sh

It correctly picks up .clang-format settings.
For issue #92 and related.

Use default style for clang-format

---

docs/clang_tidy.md
docs/user_doc.md
scripts/phabtalk/phabtalk.py

- add links to join beta and report issue
- add link "not useful" to clang-tidy warning
- clang-tidy comment in report now tells how many inline comments were
added

   Update bot report

---

scripts/choose_projects.py
scripts/llvm-dependencies.yaml
scripts/project_dependencies.json
scripts/requirements.txt

This is a proposal to address #53, #55 : It will detect which projects are affected by a patch. The scripts expects a unified diff via stdin.
For testing, run this from your llvm-project dir:
`git diff HEAD~1 | ../llvm-premerge-checks/scripts/choose_projects.py .`
This should also speed up the WIndows builds.

detect projects affected by a change

---

Jenkins/Phabricator-pipeline/Jenkinsfile
Jenkins/Phabricator-windows-pipeline/Jenkinsfile
scripts/phabtalk/phabtalk.py

Right now we have two "summary" reported. Adding a --name param to have "summary linux" and "summary windows" instead.

Add name of build agent to summary

---

scripts/phabtalk/phabtalk.py

If clang format diff is longer that 11 lines only show first 10 and add
note about omitted ones.
for #144

Truncate clang-format comments

---

scripts/choose_projects.py
scripts/llvm-dependencies.yaml
scripts/run_cmake.py
scripts/run_cmake_config.yaml
scripts/run_ninja.py

Part of #150 
Move all of the build scripting to Python:
1. clean up the existing scripts
1. use identical scripts on Linux and Windows
1. IMHO: Python simpler to use and has better error handling that Powershell
So far I migrated: run_cmake and run_ninja
Progress:

migrate scripts to python

---

containers/agent-debian-testing-buildkite/Dockerfile
containers/agent-debian-testing-buildkite/start_agent.sh
kubernetes/buildkite/agents_premerge.yaml

maybe we will later use same agents for everything but for now I don't
want to modify working build much. But I have updated deployment of
release agent to use correct docker image (there were renamed a while
ago) and pass tags and agent token via env variables.
Have not deployed new deployment for release yet.

Add new deployment for agent that will do premerge checks

---

containers/buildkite-premerge-debian/Dockerfile
containers/buildkite-premerge-debian/start_agent.sh
kubernetes/buildkite/agents_premerge.yaml
kubernetes/phabricator-proxy/Deployment.yaml
kubernetes/phabricator-proxy/Ingress.yaml
kubernetes/phabricator-proxy/Services.yaml
kubernetes/phabricator-proxy/kustomization.yaml
kubernetes/store_ssh_key.sh
phabricator-proxy/Dockerfile
phabricator-proxy/README.md
phabricator-proxy/build_deploy.sh
phabricator-proxy/main.py
scripts/buildkite/apply_patch.sh

Harbormaster can send a request in url encoded form while buildkite
expects a POST request with json. Instead of modifying harbormastar or
buildkite this adds a simple proxy that accepts url encoded form and
creates a request that buildkite expects. To avoid potential abuse,
nginx asks for simple http auth credentials stored in harbormaster.
All build parameters passed by proxy are put into build metadata and as
ph_* env variables available during the build.
Secrets involved:
- harbormastert knows http-auth to proxy (stored privately and in k8
buildkite/http-auth as auth file);
- proxy knows buildkite api token (mine atm);
- build agent knows conduit API token (mine atm),
and SSH key of llvm-premerge-tests-bot (in k8 buildkite/github-ssh).
Sample build: …

Simple service to integrate harbormaster w/ buildkite

---

containers/buildkite-premerge-debian/Dockerfile
containers/buildkite-premerge-debian/start_agent.sh
kubernetes/buildkite/agents_premerge.yaml
phabricator-proxy/main.py
scripts/buildkite/apply_patch.sh
scripts/buildkite/build_branch_pipeline.py
scripts/buildkite/create_branch_pipeline.py
scripts/phabtalk/apply_patch2.py

Now build run on buildkite for linux with two pipelines:
- "diff checks" creates a branch, pushes it to our fork and triggers "premerge checks". Note that apply_patch2 now supports cloning repository if it does not exist yet, repository is stored outside of build folder and will be reused between builds. That works in assumption that agent will execute one step at a time.
- "premerge checks" does the actual build for existing branch. I have not figured out yet how to properly split steps and this setup is likely to fail as soon as first command fails.
Not sure if that is much better that having everything in one pipeline but it separates branch creation and might be used for different purposes too. For users we will likely point to the "build" part only.
Example …

build on buildkite

---

.editorconfig
phabricator-proxy/main.py
scripts/buildkite/build_branch_pipeline.py
scripts/clang_format_report.py
scripts/clang_tidy_report.py
scripts/ignore_diff.py
scripts/lint.sh
scripts/phabtalk/phabtalk.py
scripts/premerge_checks.py
scripts/run_cmake.py
scripts/run_ninja.py
scripts/test_results_report.py

Rewritten most steps from sh to python and now all steps for linux are running at buildkite.
Logic of running steps is in scripts/premerge_checks.py. Now clang-format, clang-tidy, .. steps live in own XXX_report.py file instead of "phabtalk.py" and can be run independently in in working dir. Some code duplication is introduced this way, but I am planning to remove this parts from phabtalk.py later.
+ diff is now run with --no-prefix to unify reporting (sometimes it added prefixes "a/", "b/" and sometimes not)
+ added .editorconfig to fix differetn editor settings for py files (e.g. IntellijIdea has indent of 2 for py by default)
Example run: https://reviews.llvm.org/D80509

building with buildkite

---

scripts/clang-tidy.ignore

libclc implements OpenCL C, which is not actual C/C++, and implements an
external API with different naming conventions.
As clang-tidy cannot parse the source[0], just blacklist all of libclc's
sources for now.
[0]: https://buildkite.com/llvm-project/premerge-checks/builds/695

clang-tidy: Ignore all of libclc source

---

scripts/buildkite/build_branch_pipeline.py
scripts/buildkite/build_master_pipeline.py
scripts/exec_utils.py
scripts/premerge_checks.py

- Fix for #207. Previously grep was exiting with 1 and fail build if all
lines from ninja are filtered. Also piping might hide exit code of the
initial command. Now "tee" and "grep" is implemented on python level
and we get exit code of the original command.
- Fixed default value of "scripts_branch", print scripts commit;
- Added option to filter ninja output (on by default as before).
- Copied cache usege reporting and error handling from "master" branch
build to diff checks (useful for debugging).

Fix exit status

---

scripts/premerge_checks.py
scripts/test_results_report.py

XML tooks too long to load and not that helpful
+ link tell how many tests have failed
+ link is added only if something is off
+ link to `ninja all` log if that has failed

Add link to ninja log instead of XML #216

---

scripts/clang-tidy.ignore

Both files include GPU header files for which clang implicitly adds include directories. However, clang-tidy does not and therefore we get compile errors (i.e. not diagnostics that we could disable with NOLINT).

clang-tidy ignore {cuda,rocm}-runtime-wrappers.cpp

---

scripts/clang-tidy.ignore

All files include CUDA/ROCm headers, which trips up clang-tidy without --cuda-path/--rocm-path.

No clang-tidy under mlir-{cuda,rocm}-runner.

---

scripts/clang-tidy.ignore

some compiler-rt files contain architecture-specific assembly code or
complex macroses which clang-tidy can't process properly.
In case of assembly code: we can get "unknown register name "<whatever>' in asm"
In sanitizer_common_syscalls.inc we have issuels like:
"clang-tidy: error: unknown type name '__sanitizer_iovec'"

add some platform-specific asan files to clang-tidy.ignore list

---

scripts/buildkite/apply_patch.sh
scripts/phabtalk/apply_patch2.py

This allows parsing the commit message to get the Phabricator ID when triggering jobs from unrelated pipelines.

Add the Phabricator ID to the commit messages

---

scripts/phabtalk/apply_patch2.py

This allows jobs that trigger on these branches being created to access this information.

Include the Phabricator review ID in commit messages

---

scripts/choose_projects.py
scripts/metrics/analyze_jobs.ipynb
scripts/pipeline_create_branch.py
scripts/pipeline_master.py
scripts/pipeline_premerge.py
scripts/steps.py

Now it's possible to allow sub-projects to define own checks and skip
"generic" ones.
To properly accomodate affected projects that might not have special
treatment we:
1. extend the set of affected projecs with dependent (e.g. add 'libc' if
'clang' was modified)
2. add custom steps for projects that define own workflow. At the moment
it's only libcxx and it has a custom trigger pipeline so it's noop.
3. add dependent projects and run generic check on them.
To illustrate: imagine that we have a dependency graph:
llvm -> clang -> openmp
and only clang was modified in a diff; also clang defines own checks.
Thus list of affected projects will be [clang, openmp].
After adding custom checks and removing their projecst: [openmp].
After adding dependencies: [llvm, clang, openmp]. Generic linux / …

Allow projects to define custom steps

---

scripts/choose_projects.py
scripts/pipeline_premerge.py

Previously list of projects was resolved when job run at target OS.
Now project resolution is moved to the premerge pipeline and logic
should be there.

Fix project exclusion rules

---

docs/playbooks.md
kubernetes/buildkite/linux-agents.yaml
scripts/buildkite_utils.py
scripts/pipeline_premerge.py
scripts/summary.py

Previous approach had drawbacks:
- every step had to implement exporting of results in fixed format
- if step failed then failure will not be detected
Now report step will fetch results directly from Buildkite.
Agents have to be updated to have BUILDKITE_API_TOKEN env.

Use buildkite API instead of passing stat via files

---

scripts/clang-tidy.ignore

The only C/C++ source in this directory is for test cases. Example CL: https://reviews.llvm.org/D97668

Make clang-tidy ignore debuginfo-tests

---

scripts/clang-tidy.ignore

Those bindings requires extra dependencies (like Python, pybind11) and clang-tidy fails to analyze the source files if they are not configured properly.

Exclude MLIR bindings from clang-tidy checks

---

containers/agent-windows-vs2019/Dockerfile

The main LLVM build runs fine with MSVC itself, but building libcxx isn't supported with cl.exe, only with clang-cl.
This shouldn't matter for the main LLVM build, as it still is configured to use CXX=cl (and even then, CMake defaults to cl if nothing is specified).
This, on its own, should be enough for making it possible to build libcxx in the resulting container. However, it would be more ideal for the libcxx setup if bash was available too. This can be done by adding `C:\Program Files\Git\usr\bin` to the path - however that currently breaks the main LLVM tests. With https://reviews.llvm.org/D98858 merged, it should be possible to add that directory to the path, and it would also be possible to entirely ditch GnuWin from the container. (Installing GnuWin takes a disproportionate amount …

windows: Install LLVM/Clang in the docker image

---

containers/agent-windows-vs2019/Dockerfile

The libcxx tests currently require bash to be available (although that might change), and the bash provided with Git is enough for fulfilling this need. (Bash can also be useful for running other scripts in the libcxx CI chain outside of the tests themselves.)
For the main LLVM testing, this works once https://reviews.llvm.org/D98858 is merged.
This also allows getting rid of GnuWin altogether.

windows: Add Git Bash to the path

---

containers/agent-windows-vs2019/Dockerfile

The current default version in Chocolatey (5.28) fails to install,
with the following error:
ERROR: The response content cannot be parsed because the Internet
Explorer engine is not available, or Internet Explorer's first-launch
configuration is not complete. Specify the UseBasicParsing parameter
and try again.
This is fixed in a newer version of packaging of ActivePerl, thus request
this particular version.

windows: Install a specific version of ActivePerl

---

containers/agent-windows-vs2019/Dockerfile

These tools aren't actually needed; the same tools from Git from Windows fill the same need.
This change isn't strictly needed, but it speeds up building the docker image a bit.

windows: Stop installing GnuWin

---

containers/agent-windows-vs2019/Dockerfile

Both the main and the release/12.x branches of llvm-project should
work when built in a Windows Container with Git Bash in path now.

Remove GnuWin, add Git Bash to the path

---

containers/agent-windows-vs2019/Dockerfile

The current default version in Chocolatey, 5.28, fails to install.
This was previously worked around by pinning a newer upcoming
version, 5.28.0.20210106. However this version never got approved
into Chocolatey (for unknown reasons), so it's no longer available.
Therefore instead request the previous older version, 5.24.3.2404001,
which installs correctly.

Install an older version of ActivePerl

---

kubernetes/buildkite/service-agents.yaml
scripts/pipeline_create_branch.py
scripts/pipeline_premerge.py
scripts/steps.py

added 4 agents to run a "glue" scripts to setup and report results. That should offload linux queue and, more importantly, don't block lightweight operation on running builds.
for #292

service queue

---

scripts/metrics/repo_hist.py
scripts/metrics/repo_hist_db.py

Louis said that pre-merge testing significantly reduced the number of reverts for libc++. So I'm trying to set up some metrics to show this impact in the numbers.
I'm re-writing the git history metrics scripts to use an SQL database. This should make it easier in the future to create new metrics.

[draft] first query on DB working

---

scripts/requirements.txt

mostly to bump phabricator plugin as 0.7 has issues with SSL

update python packages

---

scripts/cancel_previous_build.py

Still left to figure out:
1. How do we get the BuildKite API tokens onto builders?
2. Is it sufficient to run that script from the first job that runs in the `premerge-checks` pipeline?
The idea is that when we are about to launch a new build in the `premerge-checks` pipeline, we figure out the review we're building for and we cancel any build currently scheduled or running for that review.
Fixes #278

Add a script to cancel previously started builds for the same review

---

scripts/metrics/phab_monitoring.py
scripts/requirements.txt

This script will check the status of Phabricator and log it to a database. We can use this to measure the uptime of Phabricator.
Once we have a more sophisticated monitoring setup,this script should be integrated there.

script to log the status of phabricator to a DB

---

containers/buildkite-premerge-debian/Dockerfile
containers/buildkite-premerge-debian/entrypoint.sh
docs/playbooks.md
kubernetes/buildkite/linux-agents-test.yaml
kubernetes/buildkite/linux-agents.yaml
kubernetes/buildkite/service-agents-test.yaml

Now builds will not be dropped on cluster upgrades. That requires
container updates.

Add graceful termination period for linux agents

---

scripts/clang-tidy.ignore

See https://reviews.llvm.org/D106500 for an example of the spurious positives I would like to ignore.

Ignore clang/lib/Headers/wasm_simd128.h

---

scripts/pipeline_premerge.py

This seems like the simplest quick solution to
https://github.com/google/llvm-premerge-checks/issues/325
I didn't test this at all.
Fixes https://github.com/google/llvm-premerge-checks/issues/325

Convert all_projects to a set when there are unmapped changes

---

scripts/pipeline_main.py

libarcher tests (part of openmp) have been broken for the past few weeks, and nobody seems to care. As such, disable the openmp project. I hope this is the right place to do so.

Disable openmp tests

---

scripts/choose_projects.py

`project` is a list here, not a string.

Correctly skip project classification for utils/

---

scripts/steps.py

I created a new queue for the pre-merge checks so that they won't
compete for resources with the post-merge build already running.
Obviously that creates some inefficiency, but is a simple way to make
sure neither build gets starved (in particular, we know that the current
setup of 4 agents running on a single 32-core VM is enough to handle the
commit traffic on the main branch whereas pre-merge testing volume is
likely to be more unpredictable.

Switch Bazel premerge checks to use llvm-bazel-premerge queue

---

scripts/pipeline_main.py
scripts/pipeline_premerge.py

For branch runs buildkite assigns a correct commit hash.
For #344.

Only override 'head' alias

---

scripts/llvm-dependencies.yaml

I was investigating why we were building so much: it turns out that a project was renamed... back in June!
Should we make it a hard failure when the "choose_project" falls back to "all"? Seems like an invalid configuration, and while bailing out to "all" is safe, it is really not desirable.

Fix llvm-dependencies.yaml: the debuginfo-tests has been renamed into cross-project-tests

---

scripts/llvm-dependencies.yaml

It has been deleted from the LLVM repo a while ago:
https://github.com/llvm/llvm-project/commit/372bfc65deb859219270e8d467ee2918fb939599

Remove `llgo` from the list of projects

---

scripts/choose_projects.py
scripts/llvm-dependencies.yaml
scripts/pipeline_premerge.py
scripts/premerge_checks.py

The current setup is configuring the "affected projects" as well
as their dependencies, and run `ninja all` followed by
`ninja check-all`.
This is quite a pessimization for leaf project which don't need to
build and run the tests for their dependencies.
For example a patch affecting only MLIR shouldn't need to build
and run LLVM and clang tests.
This patch changes this by running checks only for the affected
project. For example a patch touching `mlir` is affecting `mlir`
and `flang`. However `flang` depends on `clang`. So the list of
projects to configure is `mlir;flang;clang;llvm;`, but we want
to test only mlir and flang ; we'll run only `ninja check-mlir
check-flang`.
In practice in this example running `ninja all` builds 5658 targets
and `ninja check-all` after that adds 716 more …

Change the premerge checks to only check the affected projects

---

scripts/choose_projects.py
scripts/llvm-dependencies.yaml

When a path can't be mapped, we fallback to a "all" project.
This was broken by the recent changes to be more selective on the
testing.

Fix fallback

---

containers/agent-windows-vs2019/Dockerfile

This bundles clang/lld and associated tools, configured for a mingw
target, with corresponding mingw sysroots.
As we already install the 'llvm' chocolatey package, which also
provides clang (defaulting to a MSVC target), add this one last in the
path. This lets 'clang' refer to the default MSVC-targeting tool, while
one can use a GCC style triple prefixed driver name, like
x86_64-w64-mingw32-clang, to use this tool.
This allows setting up a much-needed mingw configuration for the libcxx
CI.

Install llvm-mingw in the windows agent docker image

---

containers/agent-windows-vs2019/Dockerfile

The current version of Python fails to build some dependencies, but
pinning the previous version works.
ActivePerl is no longer installable via Chocolatey (neither current
nor older versions) as ActiveState don't provide the downloads
without registration any longer (and even if registered, only
provide the latest, continuously updated version for free users, which
can't match the package manager checksums), see http://disq.us/p/2ipditb
for further discussion.
Replace ActivePerl with StrawberryPerl. StrawberryPerl has other
drawbacks, as it installs a whole C/C++ toolchain as part of it,
and copies of pkg-config tools that can cause package misdetections.
Remove these after installing it, see
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/11
for discussion on the …

Fix building the agent-windows-vs2019 image

---

scripts/windows/post-checkout.ps1

It takes almost 5 minutes on windows and we don't need to run it that
often.
Fixes #375

Trigger git gc on windows only for ~5% of builds.

---

containers/buildkite-premerge-debian/Dockerfile
kubernetes/buildkite/linux-agents.yaml

This should resolve the out-of-disk problems reported in #379
Mounting an [emptyDir volume](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) for the Buildkite working directory should remove the disk space limitations from Kubernetes. So now it's only limited by the physical disc space available to the VM.
I did not check in detail but it looks like the ccache folder is also below `/var/lib/buildkite-agent` so that should be covered as well.
It might cause issues with the permissions. In that case we would probably need to change the permissions after the volume is mounted. So that would have to go into the `entrypoint.sh` script.
@metaflow Can you please review the change? I did not dare to apply it so far...

Adding an `emptyDir` to kubernetes deployment

---

docs/monitoring_main_branch.md

This document proposes a design to improve the stability of the LLVM main branch
for use in pre-merge testing.
This is related to the discussion we started in #169
@joker-eph FYI, as we discussed this in the past.
@gkistanova please let me know if this would be a reasonable design from the Buildbot perspective.

Design for buildbot worker to check main branch.

---

README.md

These appear to be enabled and functioning fine. I see builds running
right now.

Revert status note about pre-merge checks being disabled

---

containers/agent-windows-vs2019/Dockerfile

(The chocolatey package of LLVM has been updated to 14.0.0 now too, so rebuilding the docker image should pick that up too, if it gets rebuilt from scratch.)

Update to the latest release of llvm-mingw (based on LLVM 14.0.0)

---

scripts/steps.py

In https://reviews.llvm.org/D123481 we're removing this from the
default builds, but we still want it in CI builds where we know the
platform and compiler configuration.

[Bazel] Explicitly build with `-Werror`

---

scripts/steps.py

This fixes the broken premerge bots.
--config=ci implicitly implies all of the removed flags via .bazelrc, except --config=rbe which was removed.

Use --config=ci on bazel premerge bots

---

scripts/patch_diff.py

We remove this functionality since it does not take into account reverted revisions.
Signed-off-by: Matheus Izvekov <mizvekov@gmail.com>

patch_diff: Stop trying to skip landed revisions

---

scripts/llvm-dependencies.yaml
scripts/run_cmake_config.yaml

Locally, disabling the fuzzer (already globally disabled) plus the ORC tests makes everything else pass.
This may need to be reverted if some tests end up failing on the Windows bots or are flaky.

Enable compiler-rt tests on Windows
